#!/usr/bin/env python
from __future__ import with_statement
import os
import sys
from optparse import OptionParser
from ConfigParser import RawConfigParser
from os.path import join, expanduser, exists, basename
from urllib import quote

def shell_escape(value):
    return r'\''.join("'%s'" % _ for _ in value.split("'"))

usage = """%prog [options] file...

Shares all the specified files and gives you links, ready to paste to selected friends or enemies."""

parser = OptionParser(usage = usage, version="%prog 0.1")
parser.add_option('-d', '--dropbox', dest='dropbox',
    default = 'default', help='Which of the defined in the config dropboxes to use, default is "default"')
parser.add_option('-c', '--config', dest = 'config_filename',
    default = join(expanduser('~'), '.mess'), help = 'What config file to use, default is $HOME/.mess. See this file for file format details.')
options, args = parser.parse_args()

dropbox = {
    'type': 'scp',
    'user': 'you',
    'host': 'example.org',
    'remote-path': 'public_html/dropbox',
    'url': 'http://example.org/dropbpox/$filename',
    'scp-options': '',
}

config = RawConfigParser(dropbox)
config.readfp(open(options.config_filename))

if not config.has_section(options.dropbox):
    parser.error("The dropbox '%s' doesn't exists! Check the config file: %s" % (options.dropbox, options.config_filename))

for var in dropbox:
    dropbox[var] = config.get(options.dropbox, var)

if 'example' in dropbox['url'] or 'example' in dropbox['host']:
    parser.error("Please, adjust your configuration file: %s" % options.config_filename)

if len(args) < 1:
    parser.error('You have to share at least one file')

cmdline = "scp -q %(options)s %(files)s %(user)s@%(host)s:%(path)s" % {
    'options': dropbox['scp-options'],
    'files': ' '.join(map(shell_escape, args)),
    'user': dropbox['user'],
    'host': dropbox['host'].strip('/').replace('http://', ''),
    'path': dropbox['remote-path'].lstrip(':').rstrip('/'),
}

if os.system(cmdline) == 0:
    copied = ''
    args = map(lambda arg: join(dropbox['url'], quote(basename(arg))), args)
    if 'darwin' == sys.platform:
        with os.popen('pbcopy', 'w') as clipboard:
            clipboard.write(args[0])
            copied = args[0]            
    print 'Shared files:'
    for url in args:
        print url + (' (copied in clipboard)' if url == copied else '')